homeassistant:
  # Name of the location where Home Assistant is running
  # name: Jones Home
  # Location required to calculate the time the sun rises and sets
  # latitude: 27.871730
  # longitude: -82.710720
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # elevation: 4
  # metric for Metric, imperial for Imperial
  # unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Add logging levels - debug is the default
logger:
  default: warn

# Enables the frontend
frontend:

# Enables Lovelace
lovelace:
  mode: yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: 192.168.1.120:8123
  # api_password: !secret http_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Set up Emulated Philips Hue Bridge
emulated_hue:
  host_ip: 192.168.1.120
  listen_port: 80
  expose_by_default: false

# Amazon Echo Integration
# alexa:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# system_health
system_health:

# Logitech Circle component
#logi_circle:
#  client_id: !secret logi_client_id
#  client_secret: !secret logi_client_secret
#  api_key: !secret logi_api
#  redirect_uri: !secret logi_uri

ifttt:
  key: !secret ifttt

tuya:
  username: !secret tuya_u
  password: !secret tuya_p
  country_code: 1
  platform: smart_life

# Universal Devices ISY994 Configuration
isy994:
  host: https://192.168.1.15:443
  username: !secret isy_username
  password: !secret isy_password

# Rest Commands
rest_command:
  isy_fridgeoff:
    url: 'http://192.168.1.15:81/rest/programs/000D/runThen'
    username: !secret isy_username
    password: !secret isy_password
  downstairs_up:
    url: 'http://192.168.1.15:81/rest/nodes/14%2029%20E4%201/cmd/BRT'
    username: !secret isy_username
    password: !secret isy_password
  downstairs_down:
    url: 'http://192.168.1.15:81/rest/nodes/14%2029%20E4%201/cmd/DIM'
    username: !secret isy_username
    password: !secret isy_password
  gavin_on:
    url: 'http://192.168.1.15:81/rest/programs/000C/enable'
    username: !secret isy_username
    password: !secret isy_password
  gavin_off:
    url: 'http://192.168.1.15:81/rest/programs/000C/disable'
    username: !secret isy_username
    password: !secret isy_password
  guest_on:
    url: 'http://192.168.1.15:81/rest/vars/set/2/3/1'
    username: !secret isy_username
    password: !secret isy_password
  guest_off:
    url: 'http://192.168.1.15:81/rest/vars/set/2/3/0'
    username: !secret isy_username
    password: !secret isy_password
  school_on:
    url: 'http://192.168.1.15:81/rest/vars/set/2/4/1'
    username: !secret isy_username
    password: !secret isy_password
  school_off:
    url: 'http://192.168.1.15:81/rest/vars/set/2/4/0'
    username: !secret isy_username
    password: !secret isy_password

# Enables a map showing the location of tracked devices
map:

zone:
  - name: Home
    latitude: 27.808933
    longitude: -82.746746
  - name: St. Pete Corps
    latitude: 27.780251
    longitude: -82.684842
  - name: St. Pete Area Command
    latitude: 27.756409
    longitude: -82.637802
  - name: St. Pete ARC
    latitude: 27.825432
    longitude: -82.727694
  - name: 74th St Elementary
    latitude: 27.807706
    longitude: -82.739408
  - name: Thurgood Marshall
    latitude: 27.749264
    longitude: -82.686692
  - name: Tbirds Practice
    latitude: 27.842464
    longitude: -82.718318

# Setup device trackers
device_tracker:
  - platform: google_maps
    username: !secret maps_username
    max_gps_accuracy: 200
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    consider_home: 600
    track_new_devices: no
    exclude:
      - 192.168.1.92
      - 192.168.1.120
      - 192.168.1.15
  - platform: automatic
    client_id: !secret automatic_id
    secret: !secret automatic_secret
    devices:
      - 2018 Chrysler Pacifica
      - 2014 Dodge Caravan

# Enable Person
person:

# Enable Z-wave
zwave:
  usb_path: /dev/ttyACM1
  network_key: !secret zwave_key

# Track the sun
sun:

# Covers
cover:
  - platform: myq
    username: !secret myq_u
    password: !secret myq_p
    type: chamberlain

# Climate
climate:
  - platform: honeywell
    username: !secret honey_u
    password: !secret honey_p
    region: us

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: command_line
    name: Alarm
    command: '/usr/bin/curl --user admin:admin "http://192.168.1.15:81/rest/programs/000C" 2>&1 | grep -oPm1 "(?<=enabled=\")[true|false]+"'
    scan_interval: 5
  - platform: command_line
    name: Fridge Program
    command: '/usr/bin/curl --user admin:admin "http://192.168.1.15:81/rest/vars/get/2/5" 2>&1 | grep -oPm1 "(?<=<val>)[^<]+"'
    scan_interval: 5
  - platform: template
    sensors:
      fridge:
        friendly_name: 'Fridge Alarm'
        value_template: >-
          {% if is_state('sensor.fridge_program', '0') %}
            Armed
          {% else %}
            Disarmed
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.fridge_program', '0') %}
            mdi:fridge
          {% else %}
            mdi:fridge-outline
          {% endif %}          
      gavins_alarm:
        friendly_name: 'Gavins Alarm'
        value_template: >
          {% if is_state("sensor.alarm", "false") %}
            Off
          {% else %}
            On
          {% endif %}
        icon_template: >
          {% if is_state("sensor.alarm", "false") %}
            mdi:alarm-off
          {% else %}
            mdi:alarm
          {% endif %}

binary_sensor:
  - platform: template
    sensors:
      motion_detector:
        device_class: motion
        friendly_name: "Motion"
        value_template: "{{  is_state('sensor.multisensor_burglar', '8') }}"
      vibration_detector:
        device_class: vibration
        friendly_name: "Vibration"
        value_template: "{{  is_state('sensor.multisensor_burglar', '3') }}"

# Push notifications for Jennifers Phone
ios:

# Logitech Harmony Hub
remote:
  - platform: harmony
    name: Harmony Hub
    host: 192.168.1.133
    activity: 20409204

# Text to speech
tts:
  - platform: google_translate
    base_url: http://192.168.0.120:8123
    service_name: google_say

group: !include_dir_merge_named groups
input_boolean: !include_dir_merge_named input_booleans
automation: !include_dir_merge_list automations
scene: !include_dir_merge_list scene
script: !include_dir_merge_named scripts
switch: !include switch.yaml
