#- platform: vesync
#  username: !secret vesync_username
#  password: !secret vesync_password
- platform: template
  switches:
    watch_xfinity:
      friendly_name: Watch TV
      value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Watch Xfinity") }}'
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Watch Xfinity'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
    watch_chromecast:
      friendly_name: Watch Chromecast
      value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Watch Chromecast") }}'
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Watch Chromecast'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
    play_xbox:
      friendly_name: Play Xbox
      value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Play Xbox 360") }}'
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Play Xbox 360'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
    watch_bluray:
      friendly_name: Watch BluRay
      value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Watch BluRay") }}'
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Watch BluRay'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
    play_wii:
      friendly_name: Play Wii
      value_template: '{{ is_state_attr("remote.harmony_hub", "current_activity", "Play Wii") }}'
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Watch Xfinity'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
