- alias: 'Bus Time'
  id: boys1
  trigger:
    - platform: time
      at: '16:45:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.guest
      state: 'off'      
  action:
    - service: script.speech_engine
      data:
        call_bus_time: 1
- alias: 'Bed Time'
  id: boys2
  trigger:
    - platform: time
      at: '20:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.guest
      state: 'off'
    - condition: state
      entity_id: input_boolean.school
      state: 'on'
  action:
    - service: script.speech_engine
      data:
        call_bed_time: 1
# new auto send command to ISY to beep if Freezer opened
# sensor.open_close_3